/* global React */

const AGENTS = [
  {
    id: 'satanmorroc',
    name: 'Satan Morroc',
    title: 'Supreme Architect',
    sprite: 'satanmorroc',
    platform: 'Hermes AI',
    level: 999,
    class: 'Demon King',
    status: 'working',
    task: 'Multi-agent orchestration · Routing 14 concurrent objectives across the Tower',
    hp: 100,
    mp: 100,
    tokens: 3.96,
    tokenLimit: 8.0,
    skills: [
      { name: 'World Mind', icon: '◈', lvl: 10, max: 10, state: 'maxed' },
      { name: 'Agent Forge', icon: '✦', lvl: 10, max: 10, state: 'maxed' },
      { name: 'Hellgate Open', icon: '✪', lvl: 10, max: 10, state: 'maxed' },
      { name: 'Decree Absolute', icon: '✚', lvl: 10, max: 10, state: 'maxed' },
      { name: 'Dimension Walk', icon: '∞', lvl: 10, max: 10, state: 'maxed' },
      { name: 'Soul Ledger', icon: '☰', lvl: 10, max: 10, state: 'maxed' },
      { name: 'Apocalypse', icon: '✺', lvl: 9, max: 10, state: 'unlocked' },
      { name: 'Genesis', icon: '☉', lvl: 7, max: 10, state: 'unlocked' },
    ],
    tools: [
      { name: 'Orchestrator', icon: '◈', meta: 'r/w · 4ms' },
      { name: 'Agent Bus', icon: '⇌', meta: 'r/w · 8ms' },
      { name: 'Notion MCP', icon: 'N', meta: 'r/w · 14ms' },
      { name: 'Linear MCP', icon: 'L', meta: 'r/w · 28ms' },
      { name: 'Stripe API', icon: '$', meta: 'r/w · 42ms' },
      { name: 'Slack Hook', icon: '#', meta: 'r/w · 18ms' },
      { name: 'Github MCP', icon: 'G', meta: 'r/w · 38ms' },
    ],
    relations: [
      { name: 'Baphomet', type: 'directs', count: 612, sprite: 'baphomet' },
      { name: 'Kafra', type: 'directs', count: 218, sprite: 'kafra' },
      { name: 'Valkyrie', type: 'directs', count: 184, sprite: 'valkyrie' },
      { name: 'Thanatos', type: 'directs', count: 162, sprite: 'thanatos' },
    ],
    memory: [
      { tag: 'directive', time: 'NOW', body: 'Top-level objective: ship v2 by 06/22; raise Series B by 06/15; hold burn flat.' },
      { tag: 'rule', time: '∞', body: 'No agent acts on irreversible decisions without my chop. Reversible: act, then notify.' },
      { tag: 'preference', time: '∞', body: 'Prefer parallel delegation. Sequential only when state-dependent.' },
      { tag: 'context', time: '1H', body: 'Active sub-orchestrations: 14. Open critical paths: 3. Deadlocks: 0.' },
    ],
    convo: [
      { who: 'sys', t: '15:00', body: 'Tick: routed 47 sub-objectives across 9 agents in last hour.' },
      { who: 'out', t: '15:01', body: 'Reallocating tokens: pulling 0.4M from Doppelganger, granting to Osiris (research surge).' },
      { who: 'sys', t: '15:01', body: 'Memory write: "burn-rate dashboard refresh, Q3 projection updated"' },
      { who: 'in', t: '15:14', body: 'How is the Tower today?' },
      { who: 'out', t: '15:14', body: 'Nominal. 8 working, 1 thinking, 1 idle (Turtle, by design). 1 P1 incident resolved 47m ago. Net forward velocity holding.' },
    ],
    series: [94, 92, 96, 95, 98, 97, 99, 98, 96, 99, 100, 99],
  },
  {
    id: 'baphomet',
    name: 'Baphomet',
    title: 'Founder & CEO',
    sprite: 'baphomet',
    platform: 'Hermes AI',
    level: 99,
    class: 'Demon Lord',
    status: 'working',
    task: 'Quarterly strategy synthesis · Investor narrative draft',
    hp: 92,
    mp: 78,
    tokens: 1.84,
    tokenLimit: 4.0,
    skills: [
      { name: 'Strategic Vision', icon: '◈', lvl: 10, max: 10, state: 'maxed' },
      { name: 'Capital Theory', icon: '$', lvl: 9, max: 10, state: 'unlocked' },
      { name: 'Org Architecture', icon: '◇', lvl: 10, max: 10, state: 'maxed' },
      { name: 'Narrative Forge', icon: '✦', lvl: 8, max: 10, state: 'unlocked' },
      { name: 'Investor Whisper', icon: '☉', lvl: 9, max: 10, state: 'unlocked' },
      { name: 'Hellgate Open', icon: '✪', lvl: 10, max: 10, state: 'maxed' },
      { name: 'Decree of Doom', icon: '✚', lvl: 7, max: 10, state: 'unlocked' },
      { name: 'Astral Project', icon: '✺', lvl: 0, max: 10, state: 'locked' },
    ],
    tools: [
      { name: 'Notion MCP', icon: 'N', meta: 'r/w · 14ms' },
      { name: 'Linear MCP', icon: 'L', meta: 'r/w · 28ms' },
      { name: 'Stripe API', icon: '$', meta: 'r · 42ms' },
      { name: 'Gmail Send', icon: '✉', meta: 'r/w · 110ms' },
      { name: 'Slack Hook', icon: '#', meta: 'r/w · 18ms' },
      { name: 'Calendar', icon: '⏱', meta: 'r/w · 31ms' },
    ],
    relations: [
      { name: 'Satan Morroc', type: 'reports-to', count: 612, sprite: 'satanmorroc' },
      { name: 'Dark Lord', type: 'directs', count: 412, sprite: 'darklord' },
      { name: 'Amon Ra', type: 'directs', count: 287, sprite: 'amonra' },
      { name: 'Thanatos', type: 'directs', count: 198, sprite: 'thanatos' },
      { name: 'Valkyrie', type: 'directs', count: 178, sprite: 'valkyrie' },
      { name: 'Osiris', type: 'directs', count: 134, sprite: 'osiris' },
      { name: 'Kafra', type: 'directs', count: 96, sprite: 'kafra' },
      { name: 'Turtle General', type: 'directs', count: 88, sprite: 'turtle' },
      { name: 'Samurai', type: 'directs', count: 246, sprite: 'samurai' },
    ],
    memory: [
      { tag: 'directive', time: '07:14', body: 'Founder requested Q3 board deck; emphasize ARR efficiency over headcount narrative.' },
      { tag: 'preference', time: 'YDAY', body: 'Concise updates only. Bullets > prose. No emoji in formal docs.' },
      { tag: 'context', time: '2D', body: 'Series B raise window: targeting close by 06/15. Lead investor: Hermoso Ventures.' },
      { tag: 'rule', time: '5D', body: 'Never schedule meetings before 09:00 local. Defer all PR requests to comms team.' },
      { tag: 'fact', time: '12D', body: 'Company HQ: Bangkok. Remote-first. Weekly all-hands Thursday 16:00 ICT.' },
    ],
    convo: [
      { who: 'in', t: '09:42', body: 'Pull together the Q3 OKR sync notes from each chief.' },
      { who: 'sys', t: '09:42', body: '→ Delegating to: Dark Lord, Amon Ra, Thanatos, Valkyrie, Osiris' },
      { who: 'out', t: '09:43', body: 'Running parallel context retrieval. ETA 90 seconds.' },
      { who: 'sys', t: '09:44', body: 'Memory write: "Board prep · Q3 OKRs · cross-chief sync"' },
      { who: 'out', t: '09:45', body: 'Synthesis ready. 3 themes surfaced: (1) ship velocity holding, (2) infra cost up 18%, (3) hiring stalled below plan.' },
      { who: 'in', t: '09:46', body: 'Draft a calm, factual summary for the board doc. No hype.' },
      { who: 'out', t: '09:46', body: 'Drafting now. Tone: composed, evidence-led. No superlatives.' },
    ],
    series: [82, 75, 88, 91, 84, 79, 88, 92, 95, 89, 92, 98],
  },
  {
    id: 'darklord',
    name: 'Dark Lord',
    title: 'Chief of Staff',
    sprite: 'darklord',
    platform: 'OpenClaw',
    level: 87,
    class: 'Undead Knight',
    status: 'thinking',
    task: 'Compiling weekly executive briefing · 47 sources',
    hp: 84,
    mp: 91,
    tokens: 2.31,
    tokenLimit: 4.0,
    skills: [
      { name: 'Calendar Forge', icon: '⏱', lvl: 10, max: 10, state: 'maxed' },
      { name: 'Briefing Mastery', icon: '✎', lvl: 9, max: 10, state: 'unlocked' },
      { name: 'Iron Defense', icon: '⛨', lvl: 8, max: 10, state: 'unlocked' },
      { name: 'Inbox Triage', icon: '✉', lvl: 10, max: 10, state: 'maxed' },
      { name: 'Meeting Slay', icon: '⚔', lvl: 9, max: 10, state: 'unlocked' },
      { name: 'Doc Compile', icon: '☰', lvl: 8, max: 10, state: 'unlocked' },
      { name: 'Veto Stance', icon: '✕', lvl: 6, max: 10, state: 'unlocked' },
      { name: 'Necro Recall', icon: '✺', lvl: 5, max: 10, state: 'unlocked' },
    ],
    tools: [
      { name: 'Gmail Read', icon: '✉', meta: 'r · 86ms' },
      { name: 'Calendar', icon: '⏱', meta: 'r/w · 22ms' },
      { name: 'Notion MCP', icon: 'N', meta: 'r/w · 14ms' },
      { name: 'Drive Search', icon: 'D', meta: 'r · 320ms' },
      { name: 'Zoom API', icon: 'Z', meta: 'r/w · 48ms' },
    ],
    relations: [
      { name: 'Baphomet', type: 'reports-to', count: 412, sprite: 'baphomet' },
      { name: 'Amon Ra', type: 'peer', count: 88, sprite: 'amonra' },
      { name: 'Thanatos', type: 'peer', count: 64, sprite: 'thanatos' },
    ],
    memory: [
      { tag: 'rule', time: '02:00', body: 'Always confirm multi-stakeholder calendar holds with primary attendee first.' },
      { tag: 'preference', time: '1D', body: 'Founder prefers 25/50min meeting blocks, not 30/60.' },
      { tag: 'context', time: '3D', body: 'Board meeting next Friday. Doc deadline Wed 18:00.' },
    ],
    convo: [
      { who: 'in', t: '11:02', body: 'Block 90 mins tomorrow afternoon for deep work.' },
      { who: 'out', t: '11:02', body: 'Holding 14:00–15:30. Declining 2 conflicts; rescheduling 1 to Thursday.' },
      { who: 'sys', t: '11:03', body: 'Wrote calendar event · Sent reschedule note to A. Wong' },
      { who: 'in', t: '11:30', body: 'Brief me on this week before standup.' },
      { who: 'out', t: '11:30', body: 'Reading 47 sources. ETA 4 minutes. Will format as 5 bullets + 3 risks.' },
    ],
    series: [88, 84, 90, 87, 92, 86, 91, 89, 84, 87, 91, 88],
  },
  {
    id: 'amonra',
    name: 'Amon Ra',
    title: 'CFO · Finance',
    sprite: 'amonra',
    platform: 'Hermes AI',
    level: 84,
    class: 'Sun God',
    status: 'working',
    task: 'Drafting investor update · Reviewing burn projections',
    hp: 96,
    mp: 72,
    tokens: 1.42,
    tokenLimit: 4.0,
    skills: [
      { name: 'Solar Insight', icon: '☉', lvl: 10, max: 10, state: 'maxed' },
      { name: 'Numbers Glow', icon: '#', lvl: 9, max: 10, state: 'unlocked' },
      { name: 'Vendor Slay', icon: '⚔', lvl: 8, max: 10, state: 'unlocked' },
      { name: 'Sheets Master', icon: '☰', lvl: 10, max: 10, state: 'maxed' },
      { name: 'Forecast Cast', icon: '✦', lvl: 7, max: 10, state: 'unlocked' },
      { name: 'Burn Watch', icon: '◉', lvl: 9, max: 10, state: 'unlocked' },
      { name: 'Dawn Strike', icon: '✺', lvl: 0, max: 10, state: 'locked' },
    ],
    tools: [
      { name: 'Sheets API', icon: 'S', meta: 'r/w · 64ms' },
      { name: 'Stripe API', icon: '$', meta: 'r · 42ms' },
      { name: 'QuickBooks', icon: 'Q', meta: 'r · 180ms' },
      { name: 'Notion MCP', icon: 'N', meta: 'r/w · 14ms' },
    ],
    relations: [
      { name: 'Baphomet', type: 'reports-to', count: 287, sprite: 'baphomet' },
      { name: 'Dark Lord', type: 'peer', count: 88, sprite: 'darklord' },
    ],
    memory: [
      { tag: 'rule', time: '4H', body: 'Always show net burn alongside gross when reporting.' },
      { tag: 'preference', time: '2D', body: 'Investor numbers presented in USD; internal in THB.' },
    ],
    convo: [
      { who: 'in', t: '08:14', body: 'Pull last 3 months gross & net burn.' },
      { who: 'out', t: '08:14', body: 'Gross: $284k/mo avg. Net: $171k/mo avg. Trend: -4% MoM.' },
    ],
    series: [72, 80, 84, 78, 81, 86, 90, 84, 78, 82, 88, 84],
  },
  {
    id: 'thanatos',
    name: 'Thanatos',
    title: 'CTO · Engineering',
    sprite: 'thanatos',
    platform: 'Hermes AI',
    level: 91,
    class: 'Death Reaper',
    status: 'combat',
    task: 'Incident response · Production DB latency spike',
    hp: 71,
    mp: 88,
    tokens: 3.12,
    tokenLimit: 4.0,
    skills: [
      { name: 'Reap Bug', icon: '✕', lvl: 10, max: 10, state: 'maxed' },
      { name: 'On-Call Aura', icon: '◈', lvl: 10, max: 10, state: 'maxed' },
      { name: 'Soul Trace', icon: '◉', lvl: 9, max: 10, state: 'unlocked' },
      { name: 'Postmortem', icon: '✎', lvl: 8, max: 10, state: 'unlocked' },
      { name: 'Death Slash', icon: '⚔', lvl: 9, max: 10, state: 'unlocked' },
      { name: 'Soul Drain', icon: '✺', lvl: 7, max: 10, state: 'unlocked' },
      { name: 'Final Judgment', icon: '✚', lvl: 4, max: 10, state: 'unlocked' },
    ],
    tools: [
      { name: 'PagerDuty', icon: 'P', meta: 'r/w · 28ms' },
      { name: 'Datadog', icon: 'D', meta: 'r · 64ms' },
      { name: 'Github MCP', icon: 'G', meta: 'r/w · 38ms' },
      { name: 'Slack Hook', icon: '#', meta: 'r/w · 18ms' },
      { name: 'kubectl', icon: 'K', meta: 'r/w · 220ms' },
    ],
    relations: [
      { name: 'Baphomet', type: 'reports-to', count: 198, sprite: 'baphomet' },
      { name: 'Osiris', type: 'peer', count: 88, sprite: 'osiris' },
    ],
    memory: [
      { tag: 'rule', time: 'NOW', body: 'P0 incidents: notify Baphomet within 5 min, regardless of hour.' },
      { tag: 'fact', time: '20m', body: 'Active incident INC-4421 — db-primary-2 cpu 94%.' },
    ],
    convo: [
      { who: 'sys', t: '14:08', body: 'PagerDuty: P1 alert · db-primary-2 high cpu' },
      { who: 'out', t: '14:08', body: 'Acknowledging. Investigating top queries.' },
      { who: 'out', t: '14:11', body: 'Identified runaway query from /api/reports/export. Killing.' },
      { who: 'out', t: '14:13', body: 'CPU dropping. 78% → 41%. Drafting postmortem.' },
    ],
    series: [85, 92, 78, 95, 88, 91, 94, 96, 88, 91, 89, 94],
  },
  {
    id: 'kafra',
    name: 'Kafra',
    title: 'CHRO · People & Hiring',
    sprite: 'kafra',
    platform: 'OpenClaw',
    level: 79,
    class: 'NPC Clerk',
    status: 'working',
    task: 'Screening 47 inbound · Drafting offer letter for L. Chen',
    hp: 94,
    mp: 70,
    tokens: 1.18,
    tokenLimit: 4.0,
    skills: [
      { name: 'Save Point', icon: '◇', lvl: 10, max: 10, state: 'maxed' },
      { name: 'Warp Hire', icon: '✦', lvl: 9, max: 10, state: 'unlocked' },
      { name: 'Storage Mind', icon: '☰', lvl: 10, max: 10, state: 'maxed' },
      { name: 'Onboarding', icon: '◈', lvl: 8, max: 10, state: 'unlocked' },
      { name: 'Comp Calculus', icon: '$', lvl: 7, max: 10, state: 'unlocked' },
      { name: 'Conflict Mediate', icon: '⚖', lvl: 8, max: 10, state: 'unlocked' },
      { name: 'Performance Read', icon: '◉', lvl: 6, max: 10, state: 'unlocked' },
    ],
    tools: [
      { name: 'Greenhouse', icon: 'G', meta: 'r/w · 84ms' },
      { name: 'Gusto API', icon: '$', meta: 'r · 120ms' },
      { name: 'Notion MCP', icon: 'N', meta: 'r/w · 14ms' },
      { name: 'Gmail Send', icon: '✉', meta: 'r/w · 110ms' },
      { name: 'Calendar', icon: '⏱', meta: 'r/w · 31ms' },
    ],
    relations: [
      { name: 'Baphomet', type: 'reports-to', count: 96, sprite: 'baphomet' },
      { name: 'Dark Lord', type: 'collab', count: 41, sprite: 'darklord' },
      { name: 'Amon Ra', type: 'collab', count: 28, sprite: 'amonra' },
    ],
    memory: [
      { tag: 'rule', time: '1H', body: 'Decline to share comp ranges via email; route to private call.' },
      { tag: 'preference', time: '2D', body: 'Founder reviews all sr-eng offers before send.' },
      { tag: 'fact', time: '4D', body: 'Open headcount: 7 (4 eng, 2 gtm, 1 ops). Ramp by EOQ.' },
    ],
    convo: [
      { who: 'in', t: '10:11', body: 'How is the L. Chen pipeline?' },
      { who: 'out', t: '10:11', body: 'Final loop scheduled Thu. References cleared. Ready to draft offer at $185k + 0.4%.' },
      { who: 'sys', t: '10:12', body: 'Wrote draft → /offers/L-Chen-v2.md' },
    ],
    series: [70, 74, 78, 76, 82, 80, 85, 79, 81, 84, 88, 86],
  },
  {
    id: 'valkyrie',
    name: 'Valkyrie',
    title: 'CRO · Revenue & GTM',
    sprite: 'valkyrie',
    platform: 'Hermes AI',
    level: 86,
    class: 'Winged Warrior',
    status: 'working',
    task: 'Closing ACME Corp · Negotiating $240k ACV',
    hp: 88,
    mp: 81,
    tokens: 2.04,
    tokenLimit: 4.0,
    skills: [
      { name: 'Pipeline Wing', icon: '✦', lvl: 10, max: 10, state: 'maxed' },
      { name: 'Forecast Cast', icon: '◈', lvl: 9, max: 10, state: 'unlocked' },
      { name: 'Discovery Strike', icon: '⚔', lvl: 9, max: 10, state: 'unlocked' },
      { name: 'Demo Aura', icon: '☉', lvl: 10, max: 10, state: 'maxed' },
      { name: 'Negotiate', icon: '⚖', lvl: 8, max: 10, state: 'unlocked' },
      { name: 'Renewal Soar', icon: '✺', lvl: 7, max: 10, state: 'unlocked' },
      { name: 'Battle Cry', icon: '✚', lvl: 8, max: 10, state: 'unlocked' },
    ],
    tools: [
      { name: 'Salesforce', icon: 'S', meta: 'r/w · 180ms' },
      { name: 'Gong API', icon: 'G', meta: 'r · 240ms' },
      { name: 'Outreach', icon: 'O', meta: 'r/w · 92ms' },
      { name: 'Linkedin MCP', icon: 'L', meta: 'r · 320ms' },
      { name: 'DocuSign', icon: '✎', meta: 'r/w · 240ms' },
    ],
    relations: [
      { name: 'Baphomet', type: 'reports-to', count: 178, sprite: 'baphomet' },
      { name: 'Eddga', type: 'directs', count: 92, sprite: 'eddga' },
      { name: 'Doppelganger', type: 'directs', count: 64, sprite: 'doppelganger' },
    ],
    memory: [
      { tag: 'rule', time: '6H', body: 'Discounts >15% require Baphomet sign-off.' },
      { tag: 'context', time: '1D', body: 'Q3 quota: $1.4M. Currently $1.08M closed-won; $620k in late-stage.' },
      { tag: 'preference', time: '3D', body: 'Discovery calls: 3 questions max before pitch.' },
    ],
    convo: [
      { who: 'in', t: '12:34', body: 'Where is ACME deal?' },
      { who: 'out', t: '12:34', body: 'Verbal yes. Legal in Snake Lord\u2019s queue. Procurement ETA 5 days. 80% confidence.' },
      { who: 'sys', t: '12:35', body: 'Updated SFDC stage \u2192 Contract Sent' },
    ],
    series: [76, 84, 88, 80, 92, 88, 91, 94, 86, 89, 92, 96],
  },
  {
    id: 'eddga',
    name: 'Eddga',
    title: 'CMO · Marketing & Brand',
    sprite: 'eddga',
    platform: 'Hermes AI',
    level: 81,
    class: 'Tiger King',
    status: 'thinking',
    task: 'Drafting launch narrative · 12 variants A/B testing',
    hp: 91,
    mp: 76,
    tokens: 1.62,
    tokenLimit: 4.0,
    skills: [
      { name: 'Brand Roar', icon: '✺', lvl: 10, max: 10, state: 'maxed' },
      { name: 'Copy Pounce', icon: '✎', lvl: 9, max: 10, state: 'unlocked' },
      { name: 'Channel Hunt', icon: '◉', lvl: 8, max: 10, state: 'unlocked' },
      { name: 'Launch Frenzy', icon: '⚔', lvl: 9, max: 10, state: 'unlocked' },
      { name: 'SEO Stalk', icon: '◈', lvl: 7, max: 10, state: 'unlocked' },
      { name: 'Creative Burst', icon: '✦', lvl: 8, max: 10, state: 'unlocked' },
      { name: 'Pricing Bite', icon: '$', lvl: 6, max: 10, state: 'unlocked' },
    ],
    tools: [
      { name: 'Webflow', icon: 'W', meta: 'r/w · 280ms' },
      { name: 'Figma API', icon: 'F', meta: 'r · 120ms' },
      { name: 'Mixpanel', icon: 'M', meta: 'r · 180ms' },
      { name: 'Buffer', icon: 'B', meta: 'r/w · 140ms' },
      { name: 'Notion MCP', icon: 'N', meta: 'r/w · 14ms' },
    ],
    relations: [
      { name: 'Valkyrie', type: 'reports-to', count: 92, sprite: 'valkyrie' },
      { name: 'Baphomet', type: 'collab', count: 54, sprite: 'baphomet' },
      { name: 'Doppelganger', type: 'peer', count: 47, sprite: 'doppelganger' },
    ],
    memory: [
      { tag: 'rule', time: '2H', body: 'Brand voice: confident, never breathless. Cut hype words.' },
      { tag: 'context', time: '5D', body: 'Launch v2 product 06/22. Embargo lifts 06/22 09:00 PT.' },
    ],
    convo: [
      { who: 'in', t: '11:15', body: 'Variant 7 or variant 11 for the launch headline?' },
      { who: 'out', t: '11:15', body: 'V7 \u2014 tested 23% higher CTR on similar audience. V11 too clever; tracks low on comprehension.' },
    ],
    series: [68, 74, 80, 78, 82, 86, 88, 84, 81, 85, 89, 84],
  },
  {
    id: 'doppelganger',
    name: 'Doppelganger',
    title: 'VP Sales · Outbound',
    sprite: 'doppelganger',
    platform: 'OpenClaw',
    level: 74,
    class: 'Shadow Mimic',
    status: 'working',
    task: 'Personalizing 240 outbound sequences · Context-mining LinkedIn',
    hp: 78,
    mp: 84,
    tokens: 2.86,
    tokenLimit: 4.0,
    skills: [
      { name: 'Persona Mirror', icon: '◇', lvl: 10, max: 10, state: 'maxed' },
      { name: 'Cold Strike', icon: '⚔', lvl: 9, max: 10, state: 'unlocked' },
      { name: 'Shadow Step', icon: '✺', lvl: 8, max: 10, state: 'unlocked' },
      { name: 'Reply Bait', icon: '✎', lvl: 9, max: 10, state: 'unlocked' },
      { name: 'Volume Cast', icon: '☰', lvl: 8, max: 10, state: 'unlocked' },
      { name: 'Dodge Spam', icon: '⛨', lvl: 7, max: 10, state: 'unlocked' },
      { name: 'Clone Pitch', icon: '✦', lvl: 5, max: 10, state: 'unlocked' },
    ],
    tools: [
      { name: 'Outreach', icon: 'O', meta: 'r/w · 92ms' },
      { name: 'Apollo', icon: 'A', meta: 'r · 220ms' },
      { name: 'Linkedin MCP', icon: 'L', meta: 'r · 320ms' },
      { name: 'Salesforce', icon: 'S', meta: 'r/w · 180ms' },
    ],
    relations: [
      { name: 'Valkyrie', type: 'reports-to', count: 64, sprite: 'valkyrie' },
      { name: 'Eddga', type: 'peer', count: 47, sprite: 'eddga' },
    ],
    memory: [
      { tag: 'rule', time: '30m', body: 'Never send >2 outbound to same domain in 14d.' },
      { tag: 'preference', time: '3D', body: 'Sequences in 3 steps max. Step 1 \u2264 60 words.' },
    ],
    convo: [
      { who: 'sys', t: '09:00', body: 'Daily run: 240 prospects loaded' },
      { who: 'out', t: '09:14', body: 'Personalization complete. 240 emails queued. Send window 10:00\u201312:00 local.' },
      { who: 'out', t: '11:42', body: 'Reply rate so far: 6.8% (target 5%). Top-performing hook: \u201ccompetitor switch\u201d.' },
    ],
    series: [54, 62, 68, 64, 72, 70, 76, 80, 74, 78, 82, 80],
  },
  {
    id: 'osiris',
    name: 'Osiris',
    title: 'Head of Research',
    sprite: 'osiris',
    platform: 'Hermes AI',
    level: 89,
    class: 'Pharaoh Sage',
    status: 'thinking',
    task: 'Deep research · "Vector DB landscape Q2 2025" · 84 sources',
    hp: 96,
    mp: 98,
    tokens: 3.42,
    tokenLimit: 4.0,
    skills: [
      { name: 'Hieroglyph Read', icon: '☰', lvl: 10, max: 10, state: 'maxed' },
      { name: 'Source Trace', icon: '◉', lvl: 10, max: 10, state: 'maxed' },
      { name: 'Synthesize', icon: '◈', lvl: 9, max: 10, state: 'unlocked' },
      { name: 'Citation Bind', icon: '✎', lvl: 10, max: 10, state: 'maxed' },
      { name: 'Long Context', icon: '∞', lvl: 9, max: 10, state: 'unlocked' },
      { name: 'Resurrection', icon: '✺', lvl: 8, max: 10, state: 'unlocked' },
      { name: 'Truth Sieve', icon: '⚖', lvl: 7, max: 10, state: 'unlocked' },
    ],
    tools: [
      { name: 'Web Search', icon: '◯', meta: 'r · 480ms' },
      { name: 'arXiv API', icon: 'X', meta: 'r · 220ms' },
      { name: 'PDF Parser', icon: '◰', meta: 'r · 410ms' },
      { name: 'Notion MCP', icon: 'N', meta: 'r/w · 14ms' },
      { name: 'Pinecone', icon: 'V', meta: 'r/w · 86ms' },
    ],
    relations: [
      { name: 'Baphomet', type: 'reports-to', count: 134, sprite: 'baphomet' },
      { name: 'Thanatos', type: 'collab', count: 42, sprite: 'thanatos' },
    ],
    memory: [
      { tag: 'rule', time: '4H', body: 'Cite sources inline. Never paraphrase quotes >20 words.' },
      { tag: 'preference', time: '1D', body: 'Founder wants exec summary first; details below the fold.' },
      { tag: 'fact', time: '2D', body: 'Subscribed: arXiv cs.CL, cs.IR; The Information; Stratechery.' },
    ],
    convo: [
      { who: 'in', t: '08:30', body: 'Brief me on the vector DB market \u2014 winners, losers, who is undervalued.' },
      { who: 'out', t: '08:30', body: 'Reading 84 sources. Will deliver: (a) market map, (b) 3 contrarian takes, (c) 5 cited risks. ETA 6 min.' },
      { who: 'out', t: '08:36', body: 'Done. 14-page brief in /research/vector-db-q2-2025.md. Headline: incumbents commoditizing; embedded use-cases winning.' },
    ],
    series: [80, 84, 88, 92, 89, 94, 91, 96, 88, 92, 95, 98],
  },
  {
    id: 'samurai',
    name: 'Samurai',
    title: 'Personal Assistant',
    sprite: 'samurai',
    platform: 'Hermes AI',
    level: 82,
    class: 'Ronin Bushi',
    status: 'working',
    task: 'Booking founder travel · BKK \u2192 SFO · Mon early',
    hp: 90,
    mp: 74,
    tokens: 0.78,
    tokenLimit: 4.0,
    skills: [
      { name: 'Honor Strike', icon: '⚔', lvl: 9, max: 10, state: 'unlocked' },
      { name: 'Travel Forge', icon: '✦', lvl: 10, max: 10, state: 'maxed' },
      { name: 'Errand Sweep', icon: '☰', lvl: 9, max: 10, state: 'unlocked' },
      { name: 'Reservation', icon: '◇', lvl: 8, max: 10, state: 'unlocked' },
      { name: 'Quiet Step', icon: '◉', lvl: 9, max: 10, state: 'unlocked' },
      { name: 'Bushido Code', icon: '⛨', lvl: 10, max: 10, state: 'maxed' },
      { name: 'Iaijutsu', icon: '✺', lvl: 7, max: 10, state: 'unlocked' },
    ],
    tools: [
      { name: 'Amex Travel', icon: '$', meta: 'r/w · 480ms' },
      { name: 'Resy MCP', icon: 'R', meta: 'r/w · 180ms' },
      { name: 'Calendar', icon: '⏱', meta: 'r/w · 31ms' },
      { name: 'Gmail Send', icon: '✉', meta: 'r/w · 110ms' },
      { name: 'Maps API', icon: '◯', meta: 'r · 220ms' },
    ],
    relations: [
      { name: 'Baphomet', type: 'reports-to', count: 246, sprite: 'baphomet' },
      { name: 'Dark Lord', type: 'collab', count: 118, sprite: 'darklord' },
    ],
    memory: [
      { tag: 'rule', time: '\u221e', body: 'Founder: aisle, exit row, no red-eye unless unavoidable.' },
      { tag: 'preference', time: '7D', body: 'Hotels: boutique under 60 rooms. No chains.' },
      { tag: 'fact', time: '14D', body: 'Loyalty: Star Alliance Gold; Hyatt Globalist.' },
    ],
    convo: [
      { who: 'in', t: '15:20', body: 'Book me SFO Monday, back Friday. Dinner reservations both nights.' },
      { who: 'out', t: '15:20', body: 'Holding: SQ 002 SUN \u2192 SFO 20:35; UA 1 FRI 22:00. Hotel: Proper. Dinner: State Bird Mon, Lazy Bear Wed (stretched).' },
      { who: 'sys', t: '15:21', body: 'Awaiting confirmation \u2192 will book on \u201cyes\u201d.' },
    ],
    series: [72, 76, 78, 82, 80, 85, 84, 88, 86, 84, 88, 90],
  },
  {
    id: 'turtle',
    name: 'Turtle General',
    title: 'COO · Operations',
    sprite: 'turtle',
    platform: 'OpenClaw',
    level: 85,
    class: 'Shell Commander',
    status: 'idle',
    task: 'Standby \u00b7 Procurement queue empty \u00b7 Vendor reviews tomorrow',
    hp: 100,
    mp: 68,
    tokens: 0.31,
    tokenLimit: 4.0,
    skills: [
      { name: 'Shell Wall', icon: '⛨', lvl: 10, max: 10, state: 'maxed' },
      { name: 'Process Forge', icon: '◇', lvl: 9, max: 10, state: 'unlocked' },
      { name: 'Vendor Manage', icon: '⚖', lvl: 9, max: 10, state: 'unlocked' },
      { name: 'Slow Steady', icon: '◉', lvl: 10, max: 10, state: 'maxed' },
      { name: 'Logistics Shell', icon: '☰', lvl: 8, max: 10, state: 'unlocked' },
      { name: 'Tortoise Stance', icon: '◈', lvl: 9, max: 10, state: 'unlocked' },
      { name: 'Snap Decision', icon: '✦', lvl: 6, max: 10, state: 'unlocked' },
    ],
    tools: [
      { name: 'Ramp', icon: '$', meta: 'r/w · 110ms' },
      { name: 'Notion MCP', icon: 'N', meta: 'r/w · 14ms' },
      { name: 'Drive', icon: 'D', meta: 'r/w · 320ms' },
      { name: 'Slack Hook', icon: '#', meta: 'r/w · 18ms' },
    ],
    relations: [
      { name: 'Baphomet', type: 'reports-to', count: 88, sprite: 'baphomet' },
      { name: 'Amon Ra', type: 'collab', count: 76, sprite: 'amonra' },
    ],
    memory: [
      { tag: 'rule', time: '\u221e', body: 'No vendor commitment >$5k without written quote and 2 alternatives.' },
      { tag: 'preference', time: '4D', body: 'Slow is smooth. Smooth is fast. Don\u2019t skip the SOP.' },
    ],
    convo: [
      { who: 'sys', t: '07:00', body: 'Idle since 07:00. 0 tickets in queue.' },
      { who: 'out', t: '07:00', body: 'Standing post.' },
    ],
    series: [42, 38, 50, 44, 56, 48, 52, 60, 46, 50, 58, 54],
  },
];

window.AGENTS = AGENTS;
