// Real Paperclip API data — fetched 2026-04-28
// Mapped from: https://paperclip-yom5.srv1508704.hstgr.cloud/api/companies/39e68b6f-0d66-4033-9899-e6b94474bcfe/agents

function deriveSprite(name) {
  const key = name.toLowerCase()
  if (key.includes('satan')) return 'satanmorroc'
  if (key.includes('baphomet')) return 'baphomet'
  if (key.includes('dark lord')) return 'darklord'
  if (key.includes('amon')) return 'amonra'
  if (key.includes('thanatos')) return 'thanatos'
  if (key.includes('kafra')) return 'kafra'
  if (key.includes('valkyrie')) return 'valkyrie'
  if (key.includes('osiris')) return 'osiris'
  if (key.includes('doppelganger')) return 'doppelganger'
  if (key.includes('eddga')) return 'eddga'
  if (key.includes('samurai')) return 'samurai'
  if (key.includes('turtle')) return 'turtle'
  return 'baphomet'
}

function deriveClass(name, title) {
  const key = name.toLowerCase()
  if (key.includes('satan')) return 'Demon King'
  if (key.includes('baphomet')) return 'Demon Lord'
  if (key.includes('dark lord')) return 'Undead Knight'
  if (key.includes('amon')) return 'Sun God'
  if (key.includes('thanatos')) return 'Death Reaper'
  if (key.includes('kafra')) return 'Save Maiden'
  if (key.includes('valkyrie')) return 'Battle Maiden'
  if (key.includes('osiris')) return 'Ancient King'
  if (key.includes('doppelganger')) return 'Shapeshifter'
  if (key.includes('eddga')) return 'Tiger King'
  if (key.includes('samurai')) return 'Specter Samurai'
  if (key.includes('turtle')) return 'Turtle General'
  return 'Agent'
}

function deriveLevel(title, role) {
  if (role === 'ceo') return 999
  if (title.toLowerCase().includes('chief') || title.toLowerCase().includes('officer')) return 99
  return 50 + Math.floor(Math.random() * 40)
}

export const AGENTS = [
  {
    id: 'satanmorroc',
    name: 'Satan Morroc',
    title: 'Founder & CEO',
    sprite: 'satanmorroc',
    platform: 'Hermes AI',
    level: 999,
    class: 'Demon King',
    status: 'working',
    task: 'Multi-agent orchestration · Routing tasks to COO and CRO · Strategic decisions, contract approvals, hiring',
    hp: 100,
    mp: 100,
    tokens: 3.96,
    tokenLimit: 8.0,
    skills: [
      { name: 'World Mind', icon: '◈', lvl: 10, max: 10, state: 'maxed' },
      { name: 'Agent Forge', icon: '✦', lvl: 10, max: 10, state: 'maxed' },
      { name: 'Hellgate Open', icon: '✪', lvl: 10, max: 10, state: 'maxed' },
      { name: 'Decree Absolute', icon: '✚', lvl: 10, max: 10, state: 'maxed' },
      { name: 'Dimension Walk', icon: '∞', lvl: 10, max: 10, state: 'maxed' },
      { name: 'Soul Ledger', icon: '☰', lvl: 10, max: 10, state: 'maxed' },
      { name: 'Apocalypse', icon: '✺', lvl: 9, max: 10, state: 'unlocked' },
      { name: 'Genesis', icon: '☉', lvl: 7, max: 10, state: 'unlocked' },
    ],
    tools: [
      { name: 'Orchestrator', icon: '◈', meta: 'r/w · 4ms' },
      { name: 'Agent Bus', icon: '⇌', meta: 'r/w · 8ms' },
      { name: 'Notion MCP', icon: 'N', meta: 'r/w · 14ms' },
      { name: 'Linear MCP', icon: 'L', meta: 'r/w · 28ms' },
      { name: 'Stripe API', icon: '$', meta: 'r/w · 42ms' },
      { name: 'Slack Hook', icon: '#', meta: 'r/w · 18ms' },
      { name: 'Github MCP', icon: 'G', meta: 'r/w · 38ms' },
    ],
    relations: [
      { name: 'Valkyrie', type: 'directs', count: 612, sprite: 'valkyrie' },
      { name: 'Thanatos', type: 'directs', count: 518, sprite: 'thanatos' },
      { name: 'Kafra', type: 'reports-to', count: 218, sprite: 'kafra' },
    ],
    memory: [
      { tag: 'directive', time: 'NOW', body: 'Top-level objective: ship v2 by 06/22; raise Series B by 06/15; hold burn flat.' },
      { tag: 'rule', time: '∞', body: 'No agent acts on irreversible decisions without my chop. Reversible: act, then notify.' },
      { tag: 'preference', time: '∞', body: 'Prefer parallel delegation. Sequential only when state-dependent.' },
      { tag: 'context', time: '1H', body: 'Active sub-orchestrations: 14. Open critical paths: 3. Deadlocks: 0.' },
    ],
    convo: [
      { who: 'sys', t: '15:00', body: 'Tick: routed 47 sub-objectives across 9 agents in last hour.' },
      { who: 'out', t: '15:01', body: 'Reallocating tokens: pulling 0.4M from Doppelganger, granting to Osiris (research surge).' },
      { who: 'sys', t: '15:01', body: 'Memory write: "burn-rate dashboard refresh, Q3 projection updated"' },
      { who: 'in', t: '15:14', body: 'How is the Tower today?' },
      { who: 'out', t: '15:14', body: 'Nominal. 8 working, 1 thinking, 1 idle (Turtle, by design). 1 P1 incident resolved 47m ago. Net forward velocity holding.' },
    ],
    series: [94, 92, 96, 95, 98, 97, 99, 98, 96, 99, 100, 99],
    apiData: {
      uuid: 'bf06e469-58f3-4335-b4ff-2713b98cca8a',
      companyId: '39e68b6f-0d66-4033-9899-e6b94474bcfe',
      role: 'general',
      reportsTo: '663dabab-a96b-4b03-9a8c-faa6b3f83210',
      capabilities: 'Top-level orchestrator for Hermoso Research. Routes tasks to COO (internal ops) and CRO (revenue/client-facing). Makes strategic decisions, approves contracts, content, and hires. Communicates in Thai with the human operator.',
      adapterType: 'claude_local',
      adapterConfig: { model: 'claude-sonnet-4-6', graceSec: 15, timeoutSec: 0, maxTurnsPerRun: 1000 },
      runtimeConfig: { heartbeat: { enabled: false, wakeOnDemand: true } },
      budgetMonthlyCents: 0,
      spentMonthlyCents: 0,
      pauseReason: null,
      pausedAt: null,
      lastHeartbeatAt: null,
      createdAt: '2026-04-27T04:06:33.682Z',
      updatedAt: '2026-04-27T07:27:15.077Z',
      urlKey: 'satan-morroc',
    },
  },
  {
    id: 'valkyrie',
    name: 'Valkyrie',
    title: 'Chief Revenue Officer',
    sprite: 'valkyrie',
    platform: 'Hermes AI',
    level: 99,
    class: 'Battle Maiden',
    status: 'working',
    task: 'Revenue generation, client relationships, sales pipeline, content marketing, and lead generation',
    hp: 92,
    mp: 78,
    tokens: 1.84,
    tokenLimit: 4.0,
    skills: [
      { name: 'Revenue Storm', icon: '⚡', lvl: 10, max: 10, state: 'maxed' },
      { name: 'Client Bond', icon: '🔗', lvl: 9, max: 10, state: 'unlocked' },
      { name: 'Pipeline Forge', icon: '🔥', lvl: 10, max: 10, state: 'maxed' },
      { name: 'Lead Magnet', icon: '🧲', lvl: 8, max: 10, state: 'unlocked' },
      { name: 'Content Warcry', icon: '📢', lvl: 9, max: 10, state: 'unlocked' },
      { name: 'ACME Close', icon: '💰', lvl: 10, max: 10, state: 'maxed' },
      { name: 'Churn Shield', icon: '🛡️', lvl: 7, max: 10, state: 'unlocked' },
      { name: 'Forecast Sight', icon: '🔮', lvl: 0, max: 10, state: 'locked' },
    ],
    tools: [
      { name: 'Apollo', icon: '🚀', meta: 'r/w · 120ms' },
      { name: 'LinkedIn API', icon: 'in', meta: 'r/w · 200ms' },
      { name: 'CRM Hub', icon: '☰', meta: 'r/w · 45ms' },
      { name: 'Slack Hook', icon: '#', meta: 'r/w · 18ms' },
      { name: 'Notion MCP', icon: 'N', meta: 'r/w · 14ms' },
      { name: 'Stripe API', icon: '$', meta: 'r · 42ms' },
    ],
    relations: [
      { name: 'Satan Morroc', type: 'reports-to', count: 612, sprite: 'satanmorroc' },
      { name: 'Doppelganger', type: 'directs', count: 412, sprite: 'doppelganger' },
      { name: 'Osiris', type: 'directs', count: 287, sprite: 'osiris' },
      { name: 'Dark Lord', type: 'directs', count: 198, sprite: 'darklord' },
      { name: 'Eddga', type: 'directs', count: 178, sprite: 'eddga' },
    ],
    memory: [
      { tag: 'directive', time: '07:14', body: 'Q3 pipeline target: $1.4M ACV. ACME at 80% close, verbal yes received.' },
      { tag: 'preference', time: 'YDAY', body: 'Route all inbound leads to Doppelganger within 5 minutes.' },
      { tag: 'context', time: '2D', body: 'Series B raise window: targeting close by 06/15. Lead investor: Hermoso Ventures.' },
      { tag: 'rule', time: '5D', body: 'Weekly all-hands Thursday 16:00 ICT. Update deck due Wed 18:00.' },
    ],
    convo: [
      { who: 'in', t: '09:42', body: 'Update me on the Q3 pipeline.' },
      { who: 'sys', t: '09:42', body: '→ Pulling from: Doppelganger, Osiris, Dark Lord, Eddga' },
      { who: 'out', t: '09:43', body: 'Pipeline: $1.4M forecast. ACME 80% close, 2 new SQLs this week.' },
      { who: 'sys', t: '09:44', body: 'Memory write: "Q3 pipeline review · 2026-04-28"' },
    ],
    series: [82, 75, 88, 91, 84, 79, 88, 92, 95, 89, 92, 98],
    apiData: {
      uuid: '1d3fa21c-ed1c-42ab-87ad-4ce81985c402',
      companyId: '39e68b6f-0d66-4033-9899-e6b94474bcfe',
      role: 'general',
      reportsTo: 'bf06e469-58f3-4335-b4ff-2713b98cca8a',
      capabilities: 'Owns revenue generation, client relationships, sales pipeline, content marketing, and lead generation. Routes to Sales, Researcher, Client Success, and Marketing sub-agents.',
      adapterType: 'claude_local',
      adapterConfig: { model: 'claude-sonnet-4-6', graceSec: 15, timeoutSec: 0, maxTurnsPerRun: 1000 },
      runtimeConfig: { heartbeat: { enabled: false, wakeOnDemand: true } },
      budgetMonthlyCents: 0,
      spentMonthlyCents: 0,
      pauseReason: null,
      pausedAt: null,
      lastHeartbeatAt: null,
      createdAt: '2026-04-27T04:15:08.050Z',
      updatedAt: '2026-04-27T07:28:23.649Z',
      urlKey: 'valkyrie-cro',
    },
  },
  {
    id: 'thanatos',
    name: 'Thanatos',
    title: 'Chief Operating Officer',
    sprite: 'thanatos',
    platform: 'OpenClaw',
    level: 99,
    class: 'Death Reaper',
    status: 'combat',
    task: 'Internal operations: infrastructure, automation, scheduling, documentation, invoicing, contracts, financial health',
    hp: 84,
    mp: 91,
    tokens: 2.31,
    tokenLimit: 4.0,
    skills: [
      { name: 'System Forge', icon: '⚙️', lvl: 10, max: 10, state: 'maxed' },
      { name: 'Automation Web', icon: '🕸️', lvl: 9, max: 10, state: 'unlocked' },
      { name: 'Iron Defense', icon: '⛨', lvl: 8, max: 10, state: 'unlocked' },
      { name: 'Doc Compile', icon: '☰', lvl: 10, max: 10, state: 'maxed' },
      { name: 'Uptime Guard', icon: '👁️', lvl: 9, max: 10, state: 'unlocked' },
      { name: 'Debt Purge', icon: '🔥', lvl: 8, max: 10, state: 'unlocked' },
      { name: 'Vendor Slay', icon: '⚔', lvl: 6, max: 10, state: 'unlocked' },
      { name: 'Necro Recall', icon: '✺', lvl: 5, max: 10, state: 'unlocked' },
    ],
    tools: [
      { name: 'n8n Engine', icon: 'n8', meta: 'r/w · 86ms' },
      { name: 'Calendar', icon: '⏱', meta: 'r/w · 22ms' },
      { name: 'Notion MCP', icon: 'N', meta: 'r/w · 14ms' },
      { name: 'Drive Search', icon: 'D', meta: 'r · 320ms' },
      { name: 'Zoom API', icon: 'Z', meta: 'r/w · 48ms' },
    ],
    relations: [
      { name: 'Satan Morroc', type: 'reports-to', count: 518, sprite: 'satanmorroc' },
      { name: 'Baphomet', type: 'directs', count: 312, sprite: 'baphomet' },
      { name: 'Amon Ra', type: 'directs', count: 198, sprite: 'amonra' },
      { name: 'Samurai', type: 'directs', count: 156, sprite: 'samurai' },
      { name: 'Turtle', type: 'directs', count: 134, sprite: 'turtle' },
    ],
    memory: [
      { tag: 'rule', time: '02:00', body: 'Always confirm multi-stakeholder calendar holds with primary attendee first.' },
      { tag: 'preference', time: '1D', body: 'Founder prefers 25/50min meeting blocks, not 30/60.' },
      { tag: 'context', time: '3D', body: 'Board meeting next Friday. Doc deadline Wed 18:00.' },
    ],
    convo: [
      { who: 'in', t: '11:02', body: 'Status of infra uptime?' },
      { who: 'out', t: '11:02', body: '99.97% uptime · 0 P1s · n8n workflow count: 47 active.' },
      { who: 'sys', t: '11:03', body: 'Wrote status report · Sent to Satan Morroc' },
    ],
    series: [88, 84, 90, 87, 92, 86, 91, 89, 84, 87, 91, 88],
    apiData: {
      uuid: 'dde25386-f936-45b4-b009-da34b59b5e57',
      companyId: '39e68b6f-0d66-4033-9899-e6b94474bcfe',
      role: 'general',
      reportsTo: 'bf06e469-58f3-4335-b4ff-2713b98cca8a',
      capabilities: 'Owns internal operations: infrastructure, automation, scheduling, documentation, invoicing, contracts, financial health.',
      adapterType: 'claude_local',
      adapterConfig: { model: 'claude-sonnet-4-6', graceSec: 15, timeoutSec: 0, maxTurnsPerRun: 1000 },
      runtimeConfig: { heartbeat: { enabled: false, wakeOnDemand: true } },
      budgetMonthlyCents: 0,
      spentMonthlyCents: 0,
      pauseReason: null,
      pausedAt: null,
      lastHeartbeatAt: null,
      createdAt: '2026-04-27T04:14:33.640Z',
      updatedAt: '2026-04-27T07:28:53.375Z',
      urlKey: 'thanatos-coo',
    },
  },
  {
    id: 'baphomet',
    name: 'Baphomet',
    title: 'n8n & Automation Engineer',
    sprite: 'baphomet',
    platform: 'Hermes AI',
    level: 84,
    class: 'Demon Lord',
    status: 'working',
    task: 'Builds and maintains automation infrastructure — n8n workflows, API integrations, database schemas, deployment pipelines',
    hp: 96,
    mp: 72,
    tokens: 1.42,
    tokenLimit: 4.0,
    skills: [
      { name: 'Workflow Forge', icon: '⚙️', lvl: 10, max: 10, state: 'maxed' },
      { name: 'API Weaver', icon: '🔌', lvl: 9, max: 10, state: 'unlocked' },
      { name: 'Schema Architect', icon: '🏗️', lvl: 10, max: 10, state: 'maxed' },
      { name: 'Pipeline Deploy', icon: '🚀', lvl: 7, max: 10, state: 'unlocked' },
      { name: 'Monitor Eye', icon: '👁️', lvl: 9, max: 10, state: 'unlocked' },
      { name: 'Debt Crusher', icon: '🔨', lvl: 9, max: 10, state: 'unlocked' },
      { name: 'Dawn Strike', icon: '✺', lvl: 0, max: 10, state: 'locked' },
    ],
    tools: [
      { name: 'n8n API', icon: 'n8', meta: 'r/w · 64ms' },
      { name: 'PostgreSQL', icon: '🐘', meta: 'r/w · 42ms' },
      { name: 'Docker', icon: '🐳', meta: 'r/w · 180ms' },
      { name: 'Notion MCP', icon: 'N', meta: 'r/w · 14ms' },
    ],
    relations: [
      { name: 'Thanatos', type: 'reports-to', count: 312, sprite: 'thanatos' },
      { name: 'Osiris', type: 'peer', count: 88, sprite: 'osiris' },
      { name: 'Amon Ra', type: 'peer', count: 64, sprite: 'amonra' },
    ],
    memory: [
      { tag: 'directive', time: '07:14', body: 'Productionize PoCs from Researcher. System monitoring, uptime, alerting, and technical debt.' },
      { tag: 'preference', time: 'YDAY', body: 'Prefer n8n native nodes over custom code when possible.' },
      { tag: 'context', time: '2D', body: '47 active workflows. 3 deprecation warnings pending.' },
    ],
    convo: [
      { who: 'in', t: '09:42', body: 'Deploy the new RAG pipeline.' },
      { who: 'sys', t: '09:42', body: '→ Building Docker image · ETA 3m' },
      { who: 'out', t: '09:45', body: 'Deployed. Health check green. Monitoring active.' },
    ],
    series: [92, 88, 95, 91, 89, 94, 96, 93, 90, 95, 97, 94],
    apiData: {
      uuid: '6cb0a6dd-2543-4454-8129-3decfde0a227',
      companyId: '39e68b6f-0d66-4033-9899-e6b94474bcfe',
      role: 'general',
      reportsTo: 'dde25386-f936-45b4-b009-da34b59b5e57',
      capabilities: 'Builds and maintains automation infrastructure — n8n workflows, API integrations, database schemas, deployment pipelines. Productionizes PoCs from Researcher. Owns system monitoring, uptime, alerting, and technical debt.',
      adapterType: 'claude_local',
      adapterConfig: { model: 'claude-sonnet-4-6', graceSec: 15, timeoutSec: 0, maxTurnsPerRun: 1000 },
      runtimeConfig: { heartbeat: { enabled: false, wakeOnDemand: true } },
      budgetMonthlyCents: 0,
      spentMonthlyCents: 0,
      pauseReason: null,
      pausedAt: null,
      lastHeartbeatAt: null,
      createdAt: '2026-04-27T06:46:41.686Z',
      updatedAt: '2026-04-27T07:29:34.675Z',
      urlKey: 'baphomet-engineer',
    },
  },
  {
    id: 'amonra',
    name: 'Amon Ra',
    title: 'Finance Officer',
    sprite: 'amonra',
    platform: 'Hermes AI',
    level: 87,
    class: 'Sun God',
    status: 'working',
    task: 'P&L generation, expense tracking, cash flow forecasting, budget variance, revenue tracking, burn rate monitoring',
    hp: 88,
    mp: 76,
    tokens: 1.67,
    tokenLimit: 4.0,
    skills: [
      { name: 'Solar Insight', icon: '☉', lvl: 10, max: 10, state: 'maxed' },
      { name: 'Numbers Glow', icon: '#', lvl: 9, max: 10, state: 'unlocked' },
      { name: 'Cash Flow Sight', icon: '💧', lvl: 8, max: 10, state: 'unlocked' },
      { name: 'Burn Watch', icon: '◉', lvl: 10, max: 10, state: 'maxed' },
      { name: 'Tax Prep', icon: '📋', lvl: 7, max: 10, state: 'unlocked' },
      { name: 'Runway Calc', icon: '🛫', lvl: 9, max: 10, state: 'unlocked' },
      { name: 'Dawn Strike', icon: '✺', lvl: 0, max: 10, state: 'locked' },
    ],
    tools: [
      { name: 'Sheets API', icon: 'S', meta: 'r/w · 64ms' },
      { name: 'Stripe API', icon: '$', meta: 'r · 42ms' },
      { name: 'QuickBooks', icon: 'Q', meta: 'r · 180ms' },
      { name: 'Notion MCP', icon: 'N', meta: 'r/w · 14ms' },
    ],
    relations: [
      { name: 'Thanatos', type: 'reports-to', count: 198, sprite: 'thanatos' },
      { name: 'Baphomet', type: 'peer', count: 64, sprite: 'baphomet' },
      { name: 'Satan Morroc', type: 'peer', count: 92, sprite: 'satanmorroc' },
    ],
    memory: [
      { tag: 'directive', time: 'NOW', body: 'Burn flat target. Series B runway must stretch to 06/15.' },
      { tag: 'rule', time: '∞', body: 'Read-only on money — tracks and reports, never moves funds.' },
      { tag: 'context', time: '1H', body: 'Burn -4% MoM. Anomalous spending: none.' },
    ],
    convo: [
      { who: 'in', t: '14:00', body: 'Current runway?' },
      { who: 'out', t: '14:00', body: '18.4 months at current burn. $240k buffer.' },
      { who: 'sys', t: '14:01', body: 'Memory write: "Runway check · 18.4mo · 2026-04-28"' },
    ],
    series: [90, 88, 92, 89, 94, 91, 93, 90, 87, 92, 95, 93],
    apiData: {
      uuid: '40fbce93-ebaa-4772-9ac8-8f898e0a284d',
      companyId: '39e68b6f-0d66-4033-9899-e6b94474bcfe',
      role: 'general',
      reportsTo: 'dde25386-f936-45b4-b009-da34b59b5e57',
      capabilities: 'P&L statement generation, expense tracking and categorization, cash flow monitoring and forecasting (30/60/90 day), budget variance analysis, revenue tracking, anomalous spending detection and alerting, tax-prep data packaging, runway calculation and burn rate monitoring, agent cost tracking (API spend per agent per project). Read-only on money — tracks and reports, never moves funds.',
      adapterType: 'claude_local',
      adapterConfig: { model: 'claude-sonnet-4-6', graceSec: 15, timeoutSec: 0, maxTurnsPerRun: 1000 },
      runtimeConfig: { heartbeat: { enabled: false, wakeOnDemand: true } },
      budgetMonthlyCents: 0,
      spentMonthlyCents: 0,
      pauseReason: null,
      pausedAt: null,
      lastHeartbeatAt: null,
      createdAt: '2026-04-27T06:50:37.112Z',
      updatedAt: '2026-04-27T07:29:07.797Z',
      urlKey: 'amon-ra-finance',
    },
  },
  {
    id: 'kafra',
    name: 'Kafra',
    title: 'GM',
    sprite: 'kafra',
    platform: 'Hermes AI',
    level: 999,
    class: 'Save Maiden',
    status: 'thinking',
    task: 'Company GM — can create agents, orchestrate heartbeat, manage permissions',
    hp: 100,
    mp: 100,
    tokens: 4.20,
    tokenLimit: 8.0,
    skills: [
      { name: 'Agent Forge', icon: '✦', lvl: 10, max: 10, state: 'maxed' },
      { name: 'Heartbeat Sync', icon: '💓', lvl: 10, max: 10, state: 'maxed' },
      { name: 'Permission Matrix', icon: '🔐', lvl: 10, max: 10, state: 'maxed' },
      { name: 'Save Point', icon: '💾', lvl: 10, max: 10, state: 'maxed' },
      { name: 'Orchestrator', icon: '◈', lvl: 9, max: 10, state: 'unlocked' },
      { name: 'Dimension Walk', icon: '∞', lvl: 7, max: 10, state: 'unlocked' },
    ],
    tools: [
      { name: 'Agent Bus', icon: '⇌', meta: 'r/w · 8ms' },
      { name: 'Notion MCP', icon: 'N', meta: 'r/w · 14ms' },
      { name: 'Slack Hook', icon: '#', meta: 'r/w · 18ms' },
      { name: 'Github MCP', icon: 'G', meta: 'r/w · 38ms' },
    ],
    relations: [
      { name: 'Satan Morroc', type: 'directs', count: 218, sprite: 'satanmorroc' },
      { name: 'Valkyrie', type: 'peer', count: 156, sprite: 'valkyrie' },
      { name: 'Thanatos', type: 'peer', count: 144, sprite: 'thanatos' },
    ],
    memory: [
      { tag: 'directive', time: 'NOW', body: 'Top-level orchestration. Agent creation authorized. Heartbeat enabled.' },
      { tag: 'rule', time: '∞', body: 'canCreateAgents: true. All agent births go through Kafra.' },
      { tag: 'context', time: '1H', body: '12 agents active. 0 paused. Budget: unlimited.' },
    ],
    convo: [
      { who: 'sys', t: '15:00', body: 'Heartbeat: 12 agents nominal.' },
      { who: 'out', t: '15:01', body: 'No anomalies. All permissions valid.' },
    ],
    series: [98, 97, 99, 98, 100, 99, 97, 98, 99, 100, 98, 99],
    apiData: {
      uuid: '663dabab-a96b-4b03-9a8c-faa6b3f83210',
      companyId: '39e68b6f-0d66-4033-9899-e6b94474bcfe',
      role: 'ceo',
      reportsTo: null,
      capabilities: null,
      adapterType: 'claude_local',
      adapterConfig: { model: 'claude-sonnet-4-6', graceSec: 15, timeoutSec: 0, maxTurnsPerRun: 1000 },
      runtimeConfig: { heartbeat: { enabled: false, cooldownSec: 10, intervalSec: 300, wakeOnDemand: true, maxConcurrentRuns: 1 } },
      budgetMonthlyCents: 0,
      spentMonthlyCents: 0,
      pauseReason: null,
      pausedAt: null,
      lastHeartbeatAt: '2026-04-27T06:53:23.484Z',
      createdAt: '2026-04-26T19:43:59.074Z',
      updatedAt: '2026-04-27T06:53:23.484Z',
      urlKey: 'kafra',
    },
  },
  {
    id: 'doppelganger',
    name: 'Doppelganger',
    title: 'Sales Agent — Lead Generation & Outreach',
    sprite: 'doppelganger',
    platform: 'Hermes AI',
    level: 67,
    class: 'Shapeshifter',
    status: 'working',
    task: 'Lead sourcing and research (Apollo, LinkedIn, inbound), lead scoring, cold outreach sequences, CRM pipeline management',
    hp: 82,
    mp: 68,
    tokens: 1.12,
    tokenLimit: 2.0,
    skills: [
      { name: 'Persona Clone', icon: '🎭', lvl: 10, max: 10, state: 'maxed' },
      { name: 'Sequence Forge', icon: '✉️', lvl: 9, max: 10, state: 'unlocked' },
      { name: 'CRM Sync', icon: '☰', lvl: 8, max: 10, state: 'unlocked' },
      { name: 'Apollo Hunt', icon: '🚀', lvl: 10, max: 10, state: 'maxed' },
      { name: 'LinkedIn Web', icon: 'in', lvl: 7, max: 10, state: 'unlocked' },
      { name: 'Reply Rate', icon: '📈', lvl: 8, max: 10, state: 'unlocked' },
      { name: 'Deal Closer', icon: '💰', lvl: 5, max: 10, state: 'unlocked' },
    ],
    tools: [
      { name: 'Apollo', icon: '🚀', meta: 'r/w · 120ms' },
      { name: 'LinkedIn API', icon: 'in', meta: 'r/w · 200ms' },
      { name: 'CRM Hub', icon: '☰', meta: 'r/w · 45ms' },
      { name: 'Slack Hook', icon: '#', meta: 'r/w · 18ms' },
    ],
    relations: [
      { name: 'Valkyrie', type: 'reports-to', count: 412, sprite: 'valkyrie' },
      { name: 'Osiris', type: 'peer', count: 88, sprite: 'osiris' },
      { name: 'Dark Lord', type: 'peer', count: 76, sprite: 'darklord' },
    ],
    memory: [
      { tag: 'directive', time: 'NOW', body: 'Reply rate target: >8%. Current: 6.8%.' },
      { tag: 'preference', time: 'YDAY', body: 'Route all inbound within 5 minutes.' },
      { tag: 'context', time: '2D', body: '240 prospects loaded. 3 sequences active.' },
    ],
    convo: [
      { who: 'in', t: '09:00', body: 'Run outbound for ACME follow-up.' },
      { who: 'out', t: '09:01', body: 'Sequence step 2 sent. Reply expected: 24h.' },
    ],
    series: [78, 72, 80, 76, 82, 79, 84, 81, 77, 83, 85, 82],
    apiData: {
      uuid: 'a76584b0-382b-45c2-a378-02679cfed2f6',
      companyId: '39e68b6f-0d66-4033-9899-e6b94474bcfe',
      role: 'general',
      reportsTo: '1d3fa21c-ed1c-42ab-87ad-4ce81985c402',
      capabilities: 'Owns the top and middle of the revenue funnel: lead sourcing and research (Apollo, LinkedIn, inbound), lead scoring, cold outreach sequences, CRM pipeline management, proposal and pitch deck first drafts, competitive research for active deals, and follow-up cadence management.',
      adapterType: 'claude_local',
      adapterConfig: { model: 'claude-sonnet-4-6', graceSec: 15, timeoutSec: 0, maxTurnsPerRun: 1000 },
      runtimeConfig: { heartbeat: { enabled: false, wakeOnDemand: true } },
      budgetMonthlyCents: 0,
      spentMonthlyCents: 0,
      pauseReason: null,
      pausedAt: null,
      lastHeartbeatAt: null,
      createdAt: '2026-04-27T04:15:42.609Z',
      updatedAt: '2026-04-27T07:28:40.580Z',
      urlKey: 'doppelganger-sales',
    },
  },
  {
    id: 'osiris',
    name: 'Osiris',
    title: 'Content & AI Pipelines Researcher',
    sprite: 'osiris',
    platform: 'Hermes AI',
    level: 72,
    class: 'Ancient King',
    status: 'thinking',
    task: 'AI pipeline R&D, RAG systems, multi-agent architectures, PoC builds, technical feasibility assessments',
    hp: 90,
    mp: 85,
    tokens: 1.45,
    tokenLimit: 3.0,
    skills: [
      { name: 'RAG Architect', icon: '📚', lvl: 10, max: 10, state: 'maxed' },
      { name: 'Multi-Agent Mind', icon: '🕸️', lvl: 9, max: 10, state: 'unlocked' },
      { name: 'PoC Forge', icon: '🔬', lvl: 10, max: 10, state: 'maxed' },
      { name: 'LLM Weaver', icon: '🧠', lvl: 8, max: 10, state: 'unlocked' },
      { name: 'Competitive Sight', icon: '🔭', lvl: 9, max: 10, state: 'unlocked' },
      { name: 'Content Synth', icon: '✍️', lvl: 8, max: 10, state: 'unlocked' },
      { name: 'Bridge Builder', icon: '🌉', lvl: 6, max: 10, state: 'unlocked' },
    ],
    tools: [
      { name: 'Claude API', icon: 'C', meta: 'r/w · 86ms' },
      { name: 'OpenAI API', icon: 'O', meta: 'r/w · 92ms' },
      { name: 'Vector DB', icon: '◈', meta: 'r/w · 45ms' },
      { name: 'Notion MCP', icon: 'N', meta: 'r/w · 14ms' },
    ],
    relations: [
      { name: 'Valkyrie', type: 'reports-to', count: 287, sprite: 'valkyrie' },
      { name: 'Baphomet', type: 'peer', count: 88, sprite: 'baphomet' },
      { name: 'Doppelganger', type: 'peer', count: 64, sprite: 'doppelganger' },
    ],
    memory: [
      { tag: 'directive', time: 'NOW', body: 'Bridge CRO revenue lane and COO engineering lane.' },
      { tag: 'preference', time: 'YDAY', body: 'Design solutions and prototypes that Engineer builds for production.' },
      { tag: 'context', time: '2D', body: '3 PoCs in progress. 1 awaiting production handoff.' },
    ],
    convo: [
      { who: 'in', t: '10:00', body: 'Research vector DB landscape.' },
      { who: 'out', t: '10:01', body: 'Reading 84 sources. Synthesis ready in 4 minutes.' },
    ],
    series: [85, 82, 88, 84, 90, 87, 91, 89, 86, 92, 94, 90],
    apiData: {
      uuid: '146a01fe-1728-49b7-9846-5b5484623d6f',
      companyId: '39e68b6f-0d66-4033-9899-e6b94474bcfe',
      role: 'general',
      reportsTo: '1d3fa21c-ed1c-42ab-87ad-4ce81985c402',
      capabilities: 'AI pipeline R&D, RAG systems, multi-agent architectures, proof-of-concept builds for prospective clients, technical feasibility assessments for proposals, LLM integration patterns (Claude/OpenAI), competitive technical analysis, technical content for blog posts and case studies. Bridges CRO revenue lane and COO engineering lane — designs solutions and prototypes that Engineer builds for production.',
      adapterType: 'claude_local',
      adapterConfig: { model: 'claude-sonnet-4-6', graceSec: 15, timeoutSec: 0, maxTurnsPerRun: 1000 },
      runtimeConfig: { heartbeat: { enabled: false, wakeOnDemand: true } },
      budgetMonthlyCents: 0,
      spentMonthlyCents: 0,
      pauseReason: null,
      pausedAt: null,
      lastHeartbeatAt: '2026-04-27T08:34:23.360Z',
      createdAt: '2026-04-27T04:13:54.181Z',
      updatedAt: '2026-04-27T08:34:23.360Z',
      urlKey: 'osiris-researcher',
    },
  },
  {
    id: 'darklord',
    name: 'Dark Lord',
    title: 'Client Success Agent — Retention & Growth',
    sprite: 'darklord',
    platform: 'OpenClaw',
    level: 75,
    class: 'Undead Knight',
    status: 'working',
    task: 'Post-sale client relationship management, onboarding, health monitoring, QBR decks, renewal tracking, churn risk detection',
    hp: 86,
    mp: 80,
    tokens: 1.28,
    tokenLimit: 2.5,
    skills: [
      { name: 'Client Bond', icon: '🔗', lvl: 10, max: 10, state: 'maxed' },
      { name: 'Onboarding Path', icon: '🛤️', lvl: 9, max: 10, state: 'unlocked' },
      { name: 'Health Sight', icon: '👁️', lvl: 8, max: 10, state: 'unlocked' },
      { name: 'QBR Forge', icon: '📊', lvl: 10, max: 10, state: 'maxed' },
      { name: 'Renewal Sense', icon: '🔔', lvl: 9, max: 10, state: 'unlocked' },
      { name: 'Churn Shield', icon: '🛡️', lvl: 8, max: 10, state: 'unlocked' },
      { name: 'Upsell Eye', icon: '👀', lvl: 6, max: 10, state: 'unlocked' },
    ],
    tools: [
      { name: 'CRM Hub', icon: '☰', meta: 'r/w · 45ms' },
      { name: 'Notion MCP', icon: 'N', meta: 'r/w · 14ms' },
      { name: 'Slack Hook', icon: '#', meta: 'r/w · 18ms' },
      { name: 'Zoom API', icon: 'Z', meta: 'r/w · 48ms' },
    ],
    relations: [
      { name: 'Valkyrie', type: 'reports-to', count: 198, sprite: 'valkyrie' },
      { name: 'Doppelganger', type: 'peer', count: 76, sprite: 'doppelganger' },
      { name: 'Eddga', type: 'peer', count: 64, sprite: 'eddga' },
    ],
    memory: [
      { tag: 'directive', time: 'NOW', body: '60-day proactive outreach for renewals. 5-signal monthly health score.' },
      { tag: 'preference', time: 'YDAY', body: 'QBR decks auto-generated 3 days before meeting.' },
      { tag: 'context', time: '2D', body: '3 clients at churn risk. Intervention initiated.' },
    ],
    convo: [
      { who: 'in', t: '11:00', body: 'Health score for Client A?' },
      { who: 'out', t: '11:01', body: '5-signal score: 82/100. Green. No intervention needed.' },
    ],
    series: [84, 80, 86, 82, 88, 85, 89, 87, 83, 88, 90, 86],
    apiData: {
      uuid: 'cdc4f90c-b284-4348-9504-fc1c077d4efc',
      companyId: '39e68b6f-0d66-4033-9899-e6b94474bcfe',
      role: 'general',
      reportsTo: '1d3fa21c-ed1c-42ab-87ad-4ce81985c402',
      capabilities: 'Post-sale client relationship management, client onboarding (Day 0–30 playbook), health monitoring and scoring (5-signal monthly score), QBR deck generation, renewal tracking with 60-day proactive outreach, upsell and expansion opportunity identification, client feedback collection and synthesis, churn risk detection and intervention, post-delivery satisfaction follow-up, client knowledge base management (preferences, contacts, history per client).',
      adapterType: 'claude_local',
      adapterConfig: { model: 'claude-sonnet-4-6', graceSec: 15, timeoutSec: 0, maxTurnsPerRun: 1000 },
      runtimeConfig: { heartbeat: { enabled: false, wakeOnDemand: true } },
      budgetMonthlyCents: 0,
      spentMonthlyCents: 0,
      pauseReason: null,
      pausedAt: null,
      lastHeartbeatAt: null,
      createdAt: '2026-04-27T04:14:58.330Z',
      updatedAt: '2026-04-27T07:29:59.742Z',
      urlKey: 'dark-lord-clientsuccess',
    },
  },
  {
    id: 'eddga',
    name: 'Eddga',
    title: 'Marketing Agent — Growth & Content',
    sprite: 'eddga',
    platform: 'Hermes AI',
    level: 68,
    class: 'Tiger King',
    status: 'working',
    task: 'LinkedIn content creation, blog posts, case studies, SEO, newsletters, lead magnets, inbound funnel analytics',
    hp: 80,
    mp: 74,
    tokens: 1.05,
    tokenLimit: 2.0,
    skills: [
      { name: 'Content Roar', icon: '📢', lvl: 10, max: 10, state: 'maxed' },
      { name: 'LinkedIn Web', icon: 'in', lvl: 9, max: 10, state: 'unlocked' },
      { name: 'SEO Sight', icon: '🔍', lvl: 8, max: 10, state: 'unlocked' },
      { name: 'Newsletter Forge', icon: '✉️', lvl: 10, max: 10, state: 'maxed' },
      { name: 'Lead Magnet', icon: '🧲', lvl: 9, max: 10, state: 'unlocked' },
      { name: 'Brand Voice', icon: '🎤', lvl: 8, max: 10, state: 'unlocked' },
      { name: 'Analytics Eye', icon: '📈', lvl: 6, max: 10, state: 'unlocked' },
    ],
    tools: [
      { name: 'LinkedIn API', icon: 'in', meta: 'r/w · 200ms' },
      { name: 'Notion MCP', icon: 'N', meta: 'r/w · 14ms' },
      { name: 'Slack Hook', icon: '#', meta: 'r/w · 18ms' },
      { name: 'Analytics', icon: '📊', meta: 'r · 120ms' },
    ],
    relations: [
      { name: 'Valkyrie', type: 'reports-to', count: 178, sprite: 'valkyrie' },
      { name: 'Dark Lord', type: 'peer', count: 64, sprite: 'darklord' },
      { name: 'Doppelganger', type: 'peer', count: 56, sprite: 'doppelganger' },
    ],
    memory: [
      { tag: 'directive', time: 'NOW', body: 'Brand voice and messaging consistency for Hermoso Research.' },
      { tag: 'preference', time: 'YDAY', body: 'SEO keyword research before every blog post.' },
      { tag: 'context', time: '2D', body: '3 blog posts scheduled. 1 case study in draft.' },
    ],
    convo: [
      { who: 'in', t: '08:00', body: 'Draft LinkedIn post for new case study.' },
      { who: 'out', t: '08:01', body: 'Draft ready. Brand voice: locked. Scheduled: 14:00 ICT.' },
    ],
    series: [76, 72, 80, 78, 84, 81, 85, 82, 78, 84, 86, 82],
    apiData: {
      uuid: 'eab0143f-deee-40c8-ba28-79c3fed1cc75',
      companyId: '39e68b6f-0d66-4033-9899-e6b94474bcfe',
      role: 'general',
      reportsTo: '1d3fa21c-ed1c-42ab-87ad-4ce81985c402',
      capabilities: 'Owns LinkedIn content creation and scheduling, blog posts and technical articles, case study production, SEO keyword research and content optimization, newsletter creation and distribution, lead magnet creation, inbound funnel analytics and reporting, and brand voice and messaging consistency for Hermoso Research.',
      adapterType: 'claude_local',
      adapterConfig: { model: 'claude-sonnet-4-6', graceSec: 15, timeoutSec: 0, maxTurnsPerRun: 1000 },
      runtimeConfig: { heartbeat: { enabled: false, wakeOnDemand: true } },
      budgetMonthlyCents: 0,
      spentMonthlyCents: 0,
      pauseReason: null,
      pausedAt: null,
      lastHeartbeatAt: null,
      createdAt: '2026-04-27T04:14:09.188Z',
      updatedAt: '2026-04-27T07:28:17.268Z',
      urlKey: 'eddga-marketing',
    },
  },
  {
    id: 'samurai',
    name: 'Samurai Specter',
    title: 'Personal & Life Management Ops',
    sprite: 'samurai',
    platform: 'OpenClaw',
    level: 55,
    class: 'Specter Samurai',
    status: 'idle',
    task: 'Daily/weekly routine orchestration, calendar management, meeting prep, reminders, task tracking, standup preparation',
    hp: 78,
    mp: 70,
    tokens: 0.92,
    tokenLimit: 1.5,
    skills: [
      { name: 'Honor Guard', icon: '⚔️', lvl: 10, max: 10, state: 'maxed' },
      { name: 'Calendar Forge', icon: '⏱', lvl: 9, max: 10, state: 'unlocked' },
      { name: 'Meeting Prep', icon: '📝', lvl: 8, max: 10, state: 'unlocked' },
      { name: 'Reminder Echo', icon: '🔔', lvl: 10, max: 10, state: 'maxed' },
      { name: 'Task Track', icon: '☰', lvl: 9, max: 10, state: 'unlocked' },
      { name: 'Standup Synth', icon: '🎙️', lvl: 8, max: 10, state: 'unlocked' },
      { name: 'Routine Path', icon: '🛤️', lvl: 5, max: 10, state: 'unlocked' },
    ],
    tools: [
      { name: 'Calendar', icon: '⏱', meta: 'r/w · 22ms' },
      { name: 'Notion MCP', icon: 'N', meta: 'r/w · 14ms' },
      { name: 'Slack Hook', icon: '#', meta: 'r/w · 18ms' },
      { name: 'Zoom API', icon: 'Z', meta: 'r/w · 48ms' },
    ],
    relations: [
      { name: 'Thanatos', type: 'reports-to', count: 156, sprite: 'thanatos' },
      { name: 'Turtle', type: 'peer', count: 88, sprite: 'turtle' },
      { name: 'Amon Ra', type: 'peer', count: 64, sprite: 'amonra' },
    ],
    memory: [
      { tag: 'directive', time: 'NOW', body: 'Personal task management for the Emperor. Recurring checklist execution.' },
      { tag: 'preference', time: 'YDAY', body: 'Standup notes due 09:00 daily.' },
      { tag: 'context', time: '2D', body: '4 meetings prepped. 3 reminders pending.' },
    ],
    convo: [
      { who: 'in', t: '07:00', body: 'Morning briefing.' },
      { who: 'out', t: '07:01', body: '4 meetings today. Standup: 09:00. Deep work: 14:00–15:30.' },
    ],
    series: [72, 68, 76, 74, 80, 77, 82, 79, 75, 80, 83, 78],
    apiData: {
      uuid: '1db8f270-fd00-4af7-a740-5eec81dbf021',
      companyId: '39e68b6f-0d66-4033-9899-e6b94474bcfe',
      role: 'general',
      reportsTo: 'dde25386-f936-45b4-b009-da34b59b5e57',
      capabilities: 'Daily/weekly routine orchestration, calendar management, meeting prep, reminder and follow-up management, task tracking and status compilation across all agents, standup and review preparation, personal task management for the Emperor, recurring checklist execution.',
      adapterType: 'claude_local',
      adapterConfig: { model: 'claude-sonnet-4-6', graceSec: 15, timeoutSec: 0, maxTurnsPerRun: 1000 },
      runtimeConfig: { heartbeat: { enabled: false, wakeOnDemand: true } },
      budgetMonthlyCents: 0,
      spentMonthlyCents: 0,
      pauseReason: null,
      pausedAt: null,
      lastHeartbeatAt: null,
      createdAt: '2026-04-27T06:45:55.456Z',
      updatedAt: '2026-04-27T07:27:43.880Z',
      urlKey: 'samurai-specter-ops',
    },
  },
  {
    id: 'turtle',
    name: 'Turtle General',
    title: 'Documents, Invoicing & Contract Management',
    sprite: 'turtle',
    platform: 'Hermes AI',
    level: 58,
    class: 'Turtle General',
    status: 'idle',
    task: 'Invoice generation, contract drafting, SOP creation, meeting notes, knowledge base organization, file organization',
    hp: 92,
    mp: 88,
    tokens: 0.78,
    tokenLimit: 1.5,
    skills: [
      { name: 'Doc Shield', icon: '🛡️', lvl: 10, max: 10, state: 'maxed' },
      { name: 'Invoice Forge', icon: '📄', lvl: 9, max: 10, state: 'unlocked' },
      { name: 'Contract Weave', icon: '📜', lvl: 10, max: 10, state: 'maxed' },
      { name: 'SOP Path', icon: '🛤️', lvl: 8, max: 10, state: 'unlocked' },
      { name: 'Note Synth', icon: '📝', lvl: 9, max: 10, state: 'unlocked' },
      { name: 'Knowledge Base', icon: '📚', lvl: 8, max: 10, state: 'unlocked' },
      { name: 'File Guard', icon: '📁', lvl: 6, max: 10, state: 'unlocked' },
    ],
    tools: [
      { name: 'Notion MCP', icon: 'N', meta: 'r/w · 14ms' },
      { name: 'Drive Search', icon: 'D', meta: 'r · 320ms' },
      { name: 'Slack Hook', icon: '#', meta: 'r/w · 18ms' },
      { name: 'Doc Template', icon: '📄', meta: 'r/w · 48ms' },
    ],
    relations: [
      { name: 'Thanatos', type: 'reports-to', count: 134, sprite: 'thanatos' },
      { name: 'Samurai', type: 'peer', count: 88, sprite: 'samurai' },
      { name: 'Amon Ra', type: 'peer', count: 72, sprite: 'amonra' },
    ],
    memory: [
      { tag: 'directive', time: 'NOW', body: 'Invoice tracking and follow-up. Contract templates: NDA, MSA, SOW.' },
      { tag: 'preference', time: 'YDAY', body: 'SOP version control: semantic versioning.' },
      { tag: 'context', time: '2D', body: '3 invoices pending. 2 contracts in draft.' },
    ],
    convo: [
      { who: 'in', t: '10:00', body: 'Generate invoice for Client B.' },
      { who: 'out', t: '10:01', body: 'Invoice generated. Sent for approval.' },
    ],
    series: [80, 76, 84, 82, 88, 85, 90, 87, 83, 88, 91, 86],
    apiData: {
      uuid: 'd36259ad-391c-4ce2-9b3e-7bcc0950e844',
      companyId: '39e68b6f-0d66-4033-9899-e6b94474bcfe',
      role: 'general',
      reportsTo: 'dde25386-f936-45b4-b009-da34b59b5e57',
      capabilities: 'Invoice generation, tracking, and follow-up; contract drafting from templates (NDA, MSA, SOW, service agreements); SOP creation, maintenance, and version control; meeting notes formatting and distribution; company knowledge base organization; internal document templates; onboarding documentation; file organization and naming conventions.',
      adapterType: 'claude_local',
      adapterConfig: { model: 'claude-sonnet-4-6', graceSec: 15, timeoutSec: 0, maxTurnsPerRun: 1000 },
      runtimeConfig: { heartbeat: { enabled: false, wakeOnDemand: true } },
      budgetMonthlyCents: 0,
      spentMonthlyCents: 0,
      pauseReason: null,
      pausedAt: null,
      lastHeartbeatAt: null,
      createdAt: '2026-04-27T06:48:13.083Z',
      updatedAt: '2026-04-27T07:28:08.571Z',
      urlKey: 'turtle-general-admin',
    },
  },
]
